---
#- hosts: fortigate
- hosts: '{{Firewall_Tivit}}'
  gather_facts: no

  tasks:
  - name: TESTE 1
    raw: |
      get hardware status | grep 'Model name'
    register: teste

  - debug:
      msg: Nome do Device '{{item.stdout_lines[0]}}'
    with_items:
     - "{{teste}}"
